# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arista/inventory.v1/services.gen.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arista.inventory.v1 import inventory_pb2 as arista_dot_inventory_dot_v1_dot_inventory__pb2
from arista.time import time_pb2 as arista_dot_time_dot_time__pb2
from arista.subscriptions import subscriptions_pb2 as arista_dot_subscriptions_dot_subscriptions__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arista/inventory.v1/services.gen.proto',
  package='arista.inventory.v1',
  syntax='proto3',
  serialized_options=b'Z$arista/resources/arista/inventory.v1',
  serialized_pb=b'\n&arista/inventory.v1/services.gen.proto\x12\x13\x61rista.inventory.v1\x1a#arista/inventory.v1/inventory.proto\x1a\x16\x61rista/time/time.proto\x1a(arista/subscriptions/subscriptions.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n\rDeviceRequest\x12+\n\x03key\x18\x01 \x01(\x0b\x32\x1e.arista.inventory.v1.DeviceKey\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"f\n\x0e\x44\x65viceResponse\x12*\n\x05value\x18\x01 \x01(\x0b\x32\x1b.arista.inventory.v1.Device\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xaa\x01\n\x13\x44\x65viceStreamRequest\x12\x36\n\x11partial_eq_filter\x18\x01 \x03(\x0b\x32\x1b.arista.inventory.v1.Device\x12%\n\x04time\x18\x03 \x01(\x0b\x32\x17.arista.time.TimeBounds\x12\x34\n\x0freturned_fields\x18\x04 \x01(\x0b\x32\x1b.arista.inventory.v1.Device\"\x9b\x01\n\x14\x44\x65viceStreamResponse\x12*\n\x05value\x18\x01 \x01(\x0b\x32\x1b.arista.inventory.v1.Device\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x1f.arista.subscriptions.Operation2\xa8\x02\n\x0e\x44\x65viceResource\x12Q\n\x06GetOne\x12\".arista.inventory.v1.DeviceRequest\x1a#.arista.inventory.v1.DeviceResponse\x12_\n\x06GetAll\x12(.arista.inventory.v1.DeviceStreamRequest\x1a).arista.inventory.v1.DeviceStreamResponse0\x01\x12\x62\n\tSubscribe\x12(.arista.inventory.v1.DeviceStreamRequest\x1a).arista.inventory.v1.DeviceStreamResponse0\x01\x42&Z$arista/resources/arista/inventory.v1b\x06proto3'
  ,
  dependencies=[arista_dot_inventory_dot_v1_dot_inventory__pb2.DESCRIPTOR,arista_dot_time_dot_time__pb2.DESCRIPTOR,arista_dot_subscriptions_dot_subscriptions__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_DEVICEREQUEST = _descriptor.Descriptor(
  name='DeviceRequest',
  full_name='arista.inventory.v1.DeviceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arista.inventory.v1.DeviceRequest.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='arista.inventory.v1.DeviceRequest.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=301,
)


_DEVICERESPONSE = _descriptor.Descriptor(
  name='DeviceResponse',
  full_name='arista.inventory.v1.DeviceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='arista.inventory.v1.DeviceResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='arista.inventory.v1.DeviceResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=405,
)


_DEVICESTREAMREQUEST = _descriptor.Descriptor(
  name='DeviceStreamRequest',
  full_name='arista.inventory.v1.DeviceStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partial_eq_filter', full_name='arista.inventory.v1.DeviceStreamRequest.partial_eq_filter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='arista.inventory.v1.DeviceStreamRequest.time', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returned_fields', full_name='arista.inventory.v1.DeviceStreamRequest.returned_fields', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=578,
)


_DEVICESTREAMRESPONSE = _descriptor.Descriptor(
  name='DeviceStreamResponse',
  full_name='arista.inventory.v1.DeviceStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='arista.inventory.v1.DeviceStreamResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='arista.inventory.v1.DeviceStreamResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='arista.inventory.v1.DeviceStreamResponse.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=736,
)

_DEVICEREQUEST.fields_by_name['key'].message_type = arista_dot_inventory_dot_v1_dot_inventory__pb2._DEVICEKEY
_DEVICEREQUEST.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DEVICERESPONSE.fields_by_name['value'].message_type = arista_dot_inventory_dot_v1_dot_inventory__pb2._DEVICE
_DEVICERESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DEVICESTREAMREQUEST.fields_by_name['partial_eq_filter'].message_type = arista_dot_inventory_dot_v1_dot_inventory__pb2._DEVICE
_DEVICESTREAMREQUEST.fields_by_name['time'].message_type = arista_dot_time_dot_time__pb2._TIMEBOUNDS
_DEVICESTREAMREQUEST.fields_by_name['returned_fields'].message_type = arista_dot_inventory_dot_v1_dot_inventory__pb2._DEVICE
_DEVICESTREAMRESPONSE.fields_by_name['value'].message_type = arista_dot_inventory_dot_v1_dot_inventory__pb2._DEVICE
_DEVICESTREAMRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DEVICESTREAMRESPONSE.fields_by_name['type'].enum_type = arista_dot_subscriptions_dot_subscriptions__pb2._OPERATION
DESCRIPTOR.message_types_by_name['DeviceRequest'] = _DEVICEREQUEST
DESCRIPTOR.message_types_by_name['DeviceResponse'] = _DEVICERESPONSE
DESCRIPTOR.message_types_by_name['DeviceStreamRequest'] = _DEVICESTREAMREQUEST
DESCRIPTOR.message_types_by_name['DeviceStreamResponse'] = _DEVICESTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceRequest = _reflection.GeneratedProtocolMessageType('DeviceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEREQUEST,
  '__module__' : 'arista.inventory.v1.services.gen_pb2'
  # @@protoc_insertion_point(class_scope:arista.inventory.v1.DeviceRequest)
  })
_sym_db.RegisterMessage(DeviceRequest)

DeviceResponse = _reflection.GeneratedProtocolMessageType('DeviceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEVICERESPONSE,
  '__module__' : 'arista.inventory.v1.services.gen_pb2'
  # @@protoc_insertion_point(class_scope:arista.inventory.v1.DeviceResponse)
  })
_sym_db.RegisterMessage(DeviceResponse)

DeviceStreamRequest = _reflection.GeneratedProtocolMessageType('DeviceStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEVICESTREAMREQUEST,
  '__module__' : 'arista.inventory.v1.services.gen_pb2'
  # @@protoc_insertion_point(class_scope:arista.inventory.v1.DeviceStreamRequest)
  })
_sym_db.RegisterMessage(DeviceStreamRequest)

DeviceStreamResponse = _reflection.GeneratedProtocolMessageType('DeviceStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEVICESTREAMRESPONSE,
  '__module__' : 'arista.inventory.v1.services.gen_pb2'
  # @@protoc_insertion_point(class_scope:arista.inventory.v1.DeviceStreamResponse)
  })
_sym_db.RegisterMessage(DeviceStreamResponse)


DESCRIPTOR._options = None

_DEVICERESOURCE = _descriptor.ServiceDescriptor(
  name='DeviceResource',
  full_name='arista.inventory.v1.DeviceResource',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=739,
  serialized_end=1035,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOne',
    full_name='arista.inventory.v1.DeviceResource.GetOne',
    index=0,
    containing_service=None,
    input_type=_DEVICEREQUEST,
    output_type=_DEVICERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='arista.inventory.v1.DeviceResource.GetAll',
    index=1,
    containing_service=None,
    input_type=_DEVICESTREAMREQUEST,
    output_type=_DEVICESTREAMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='arista.inventory.v1.DeviceResource.Subscribe',
    index=2,
    containing_service=None,
    input_type=_DEVICESTREAMREQUEST,
    output_type=_DEVICESTREAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICERESOURCE)

DESCRIPTOR.services_by_name['DeviceResource'] = _DEVICERESOURCE

# @@protoc_insertion_point(module_scope)
