# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from arista.inventory.v1.services import gen_pb2 as arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2


class DeviceResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.inventory.v1.DeviceResource/GetOne',
        request_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceRequest.SerializeToString,
        response_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.inventory.v1.DeviceResource/GetAll',
        request_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.SerializeToString,
        response_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.inventory.v1.DeviceResource/Subscribe',
        request_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.SerializeToString,
        response_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.FromString,
        )


class DeviceResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceRequest.FromString,
          response_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.FromString,
          response_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamRequest.FromString,
          response_serializer=arista_dot_inventory_dot_v1_dot_services_dot_gen__pb2.DeviceStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.inventory.v1.DeviceResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
