# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from arista.tag.v1.services import gen_pb2 as arista_dot_tag_dot_v1_dot_services_dot_gen__pb2


class DeviceTagResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.tag.v1.DeviceTagResource/GetOne',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.tag.v1.DeviceTagResource/GetAll',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.tag.v1.DeviceTagResource/Subscribe',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamResponse.FromString,
        )


class DeviceTagResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceTagResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.tag.v1.DeviceTagResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DeviceTagAssignmentConfigResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.tag.v1.DeviceTagAssignmentConfigResource/GetOne',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.tag.v1.DeviceTagAssignmentConfigResource/GetAll',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.tag.v1.DeviceTagAssignmentConfigResource/Subscribe',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamResponse.FromString,
        )
    self.Set = channel.unary_unary(
        '/arista.tag.v1.DeviceTagAssignmentConfigResource/Set',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigSetRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigSetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/arista.tag.v1.DeviceTagAssignmentConfigResource/Delete',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigDeleteRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigDeleteResponse.FromString,
        )


class DeviceTagAssignmentConfigResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceTagAssignmentConfigResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigStreamResponse.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigSetRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigSetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigDeleteRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagAssignmentConfigDeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.tag.v1.DeviceTagAssignmentConfigResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DeviceTagConfigResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.tag.v1.DeviceTagConfigResource/GetOne',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.tag.v1.DeviceTagConfigResource/GetAll',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.tag.v1.DeviceTagConfigResource/Subscribe',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamResponse.FromString,
        )
    self.Set = channel.unary_unary(
        '/arista.tag.v1.DeviceTagConfigResource/Set',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigSetRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigSetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/arista.tag.v1.DeviceTagConfigResource/Delete',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigDeleteRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigDeleteResponse.FromString,
        )


class DeviceTagConfigResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceTagConfigResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigStreamResponse.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigSetRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigSetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigDeleteRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.DeviceTagConfigDeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.tag.v1.DeviceTagConfigResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class InterfaceTagResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagResource/GetOne',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.tag.v1.InterfaceTagResource/GetAll',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.tag.v1.InterfaceTagResource/Subscribe',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamResponse.FromString,
        )


class InterfaceTagResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InterfaceTagResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.tag.v1.InterfaceTagResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class InterfaceTagAssignmentConfigResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagAssignmentConfigResource/GetOne',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.tag.v1.InterfaceTagAssignmentConfigResource/GetAll',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.tag.v1.InterfaceTagAssignmentConfigResource/Subscribe',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamResponse.FromString,
        )
    self.Set = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagAssignmentConfigResource/Set',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigSetRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigSetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagAssignmentConfigResource/Delete',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigDeleteRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigDeleteResponse.FromString,
        )


class InterfaceTagAssignmentConfigResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InterfaceTagAssignmentConfigResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigStreamResponse.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigSetRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigSetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigDeleteRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagAssignmentConfigDeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.tag.v1.InterfaceTagAssignmentConfigResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class InterfaceTagConfigResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagConfigResource/GetOne',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.tag.v1.InterfaceTagConfigResource/GetAll',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.tag.v1.InterfaceTagConfigResource/Subscribe',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamResponse.FromString,
        )
    self.Set = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagConfigResource/Set',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigSetRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigSetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/arista.tag.v1.InterfaceTagConfigResource/Delete',
        request_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigDeleteRequest.SerializeToString,
        response_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigDeleteResponse.FromString,
        )


class InterfaceTagConfigResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InterfaceTagConfigResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigStreamResponse.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigSetRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigSetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigDeleteRequest.FromString,
          response_serializer=arista_dot_tag_dot_v1_dot_services_dot_gen__pb2.InterfaceTagConfigDeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.tag.v1.InterfaceTagConfigResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
