# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from arista.event.v1.services import gen_pb2 as arista_dot_event_dot_v1_dot_services_dot_gen__pb2


class EventResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.event.v1.EventResource/GetOne',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.event.v1.EventResource/GetAll',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.event.v1.EventResource/Subscribe',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamResponse.FromString,
        )


class EventResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.event.v1.EventResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class EventAnnotationConfigResourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOne = channel.unary_unary(
        '/arista.event.v1.EventAnnotationConfigResource/GetOne',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigResponse.FromString,
        )
    self.GetAll = channel.unary_stream(
        '/arista.event.v1.EventAnnotationConfigResource/GetAll',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/arista.event.v1.EventAnnotationConfigResource/Subscribe',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamResponse.FromString,
        )
    self.Set = channel.unary_unary(
        '/arista.event.v1.EventAnnotationConfigResource/Set',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigSetRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigSetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/arista.event.v1.EventAnnotationConfigResource/Delete',
        request_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigDeleteRequest.SerializeToString,
        response_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigDeleteResponse.FromString,
        )


class EventAnnotationConfigResourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EventAnnotationConfigResourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOne': grpc.unary_unary_rpc_method_handler(
          servicer.GetOne,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigStreamResponse.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigSetRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigSetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigDeleteRequest.FromString,
          response_serializer=arista_dot_event_dot_v1_dot_services_dot_gen__pb2.EventAnnotationConfigDeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'arista.event.v1.EventAnnotationConfigResource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
